remote_theme: just-the-docs/just-the-docs

title: Beemo Docs
email: hello@beemo.gg
description: Beemo is a free antispam Discord Bot that can stop userbot raids against your server.
url: https://docs.beemo.gg

aux_links:
  beemo.gg:
    - https://beemo.gg/
  Discord:
    - https://beemo.gg/discord
  GitHub:
    - https://github.com/BeemoBot/docs.beemo.gg

color_scheme: dark

heading_anchors: true

gh_edit_link: true
gh_edit_link_text: Edit on GitHub
gh_edit_repository: https://github.com/BeemoBot/docs.beemo.gg
gh_edit_branch: main
gh_edit_view_mode: tree

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 6
  preview_words_after: 6
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
